version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo 'npm installing'
      - run: npm install
      - run: CI=true npm run build
  randomrun:
    - checkout
    - run: echo 'randomrun'
workflows:
  version: 2
  build_random:
    jobs:
      - build
      - randomrun
